[build]
  command = "npm run production"
  publish = "dist"
  functions = "functions"

[build.environment]
    NODE_VERSION = "12.14.0"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "origin-when-cross-origin"
        Strict-Transport-Security= "max-age=86400"

# Netlify subdomain
[[redirects]]
    from = "https://frontend-weekly.netlify.com/*"
    to = "https://frontendweekly.tokyo/:splat"
    status = 301
    force = true

# Favicon
[[redirects]]
    from = "/favicon.ico*"
    to = "/images/favicon.png:splat"
    status = 301
